//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM 关系源元数据

[assembly: EdmRelationshipAttribute("StdMng2015NModel", "FK__t_Course__CPno__0519C6AF", "t_Course", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(StdMng2016.t_Course), "t_Course1", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(StdMng2016.t_Course), true)]
[assembly: EdmRelationshipAttribute("StdMng2015NModel", "FK__t_SC__Cno__08EA5793", "t_Course", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(StdMng2016.t_Course), "t_SC", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(StdMng2016.t_SC), true)]
[assembly: EdmRelationshipAttribute("StdMng2015NModel", "FK__t_SC__Sno__07F6335A", "t_Student", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(StdMng2016.t_Student), "t_SC", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(StdMng2016.t_SC), true)]
[assembly: EdmRelationshipAttribute("StdMng2015NModel", "FK__t_Student__SImag__023D5A04", "t_Sdept", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(StdMng2016.t_Sdept), "t_Student", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(StdMng2016.t_Student), true)]

#endregion

namespace StdMng2016
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class StdMng2015NEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“StdMng2015NEntities”部分中的连接字符串初始化新 StdMng2015NEntities 对象。
        /// </summary>
        public StdMng2015NEntities() : base("name=StdMng2015NEntities", "StdMng2015NEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 StdMng2015NEntities 对象。
        /// </summary>
        public StdMng2015NEntities(string connectionString) : base(connectionString, "StdMng2015NEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 StdMng2015NEntities 对象。
        /// </summary>
        public StdMng2015NEntities(EntityConnection connection) : base(connection, "StdMng2015NEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<t_Course> t_Course
        {
            get
            {
                if ((_t_Course == null))
                {
                    _t_Course = base.CreateObjectSet<t_Course>("t_Course");
                }
                return _t_Course;
            }
        }
        private ObjectSet<t_Course> _t_Course;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<t_SC> t_SC
        {
            get
            {
                if ((_t_SC == null))
                {
                    _t_SC = base.CreateObjectSet<t_SC>("t_SC");
                }
                return _t_SC;
            }
        }
        private ObjectSet<t_SC> _t_SC;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<t_Sdept> t_Sdept
        {
            get
            {
                if ((_t_Sdept == null))
                {
                    _t_Sdept = base.CreateObjectSet<t_Sdept>("t_Sdept");
                }
                return _t_Sdept;
            }
        }
        private ObjectSet<t_Sdept> _t_Sdept;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<t_Student> t_Student
        {
            get
            {
                if ((_t_Student == null))
                {
                    _t_Student = base.CreateObjectSet<t_Student>("t_Student");
                }
                return _t_Student;
            }
        }
        private ObjectSet<t_Student> _t_Student;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<t_MassData> t_MassData
        {
            get
            {
                if ((_t_MassData == null))
                {
                    _t_MassData = base.CreateObjectSet<t_MassData>("t_MassData");
                }
                return _t_MassData;
            }
        }
        private ObjectSet<t_MassData> _t_MassData;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 用于向 t_Course EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTot_Course(t_Course t_Course)
        {
            base.AddObject("t_Course", t_Course);
        }
    
        /// <summary>
        /// 用于向 t_SC EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTot_SC(t_SC t_SC)
        {
            base.AddObject("t_SC", t_SC);
        }
    
        /// <summary>
        /// 用于向 t_Sdept EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTot_Sdept(t_Sdept t_Sdept)
        {
            base.AddObject("t_Sdept", t_Sdept);
        }
    
        /// <summary>
        /// 用于向 t_Student EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTot_Student(t_Student t_Student)
        {
            base.AddObject("t_Student", t_Student);
        }
    
        /// <summary>
        /// 用于向 t_MassData EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTot_MassData(t_MassData t_MassData)
        {
            base.AddObject("t_MassData", t_MassData);
        }

        #endregion

    }

    #endregion

    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StdMng2015NModel", Name="t_Course")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class t_Course : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 t_Course 对象。
        /// </summary>
        /// <param name="cno">Cno 属性的初始值。</param>
        /// <param name="cName">CName 属性的初始值。</param>
        /// <param name="cCredit">CCredit 属性的初始值。</param>
        public static t_Course Createt_Course(global::System.String cno, global::System.String cName, global::System.Int16 cCredit)
        {
            t_Course t_Course = new t_Course();
            t_Course.Cno = cno;
            t_Course.CName = cName;
            t_Course.CCredit = cCredit;
            return t_Course;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Cno
        {
            get
            {
                return _Cno;
            }
            set
            {
                if (_Cno != value)
                {
                    OnCnoChanging(value);
                    ReportPropertyChanging("Cno");
                    _Cno = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Cno");
                    OnCnoChanged();
                }
            }
        }
        private global::System.String _Cno;
        partial void OnCnoChanging(global::System.String value);
        partial void OnCnoChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CName
        {
            get
            {
                return _CName;
            }
            set
            {
                OnCNameChanging(value);
                ReportPropertyChanging("CName");
                _CName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CName");
                OnCNameChanged();
            }
        }
        private global::System.String _CName;
        partial void OnCNameChanging(global::System.String value);
        partial void OnCNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CPno
        {
            get
            {
                return _CPno;
            }
            set
            {
                OnCPnoChanging(value);
                ReportPropertyChanging("CPno");
                _CPno = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CPno");
                OnCPnoChanged();
            }
        }
        private global::System.String _CPno;
        partial void OnCPnoChanging(global::System.String value);
        partial void OnCPnoChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 CCredit
        {
            get
            {
                return _CCredit;
            }
            set
            {
                OnCCreditChanging(value);
                ReportPropertyChanging("CCredit");
                _CCredit = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CCredit");
                OnCCreditChanged();
            }
        }
        private global::System.Int16 _CCredit;
        partial void OnCCreditChanging(global::System.Int16 value);
        partial void OnCCreditChanged();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StdMng2015NModel", "FK__t_Course__CPno__0519C6AF", "t_Course1")]
        public EntityCollection<t_Course> t_Course1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<t_Course>("StdMng2015NModel.FK__t_Course__CPno__0519C6AF", "t_Course1");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<t_Course>("StdMng2015NModel.FK__t_Course__CPno__0519C6AF", "t_Course1", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StdMng2015NModel", "FK__t_Course__CPno__0519C6AF", "t_Course")]
        public t_Course t_Course2
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<t_Course>("StdMng2015NModel.FK__t_Course__CPno__0519C6AF", "t_Course").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<t_Course>("StdMng2015NModel.FK__t_Course__CPno__0519C6AF", "t_Course").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<t_Course> t_Course2Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<t_Course>("StdMng2015NModel.FK__t_Course__CPno__0519C6AF", "t_Course");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<t_Course>("StdMng2015NModel.FK__t_Course__CPno__0519C6AF", "t_Course", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StdMng2015NModel", "FK__t_SC__Cno__08EA5793", "t_SC")]
        public EntityCollection<t_SC> t_SC
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<t_SC>("StdMng2015NModel.FK__t_SC__Cno__08EA5793", "t_SC");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<t_SC>("StdMng2015NModel.FK__t_SC__Cno__08EA5793", "t_SC", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StdMng2015NModel", Name="t_MassData")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class t_MassData : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 t_MassData 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        /// <param name="num">Num 属性的初始值。</param>
        /// <param name="content">Content 属性的初始值。</param>
        /// <param name="modifyDate">ModifyDate 属性的初始值。</param>
        public static t_MassData Createt_MassData(global::System.Int64 id, global::System.Int64 num, global::System.String content, global::System.DateTime modifyDate)
        {
            t_MassData t_MassData = new t_MassData();
            t_MassData.ID = id;
            t_MassData.Num = num;
            t_MassData.Content = content;
            t_MassData.ModifyDate = modifyDate;
            return t_MassData;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Num
        {
            get
            {
                return _Num;
            }
            set
            {
                OnNumChanging(value);
                ReportPropertyChanging("Num");
                _Num = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Num");
                OnNumChanged();
            }
        }
        private global::System.Int64 _Num;
        partial void OnNumChanging(global::System.Int64 value);
        partial void OnNumChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Content
        {
            get
            {
                return _Content;
            }
            set
            {
                OnContentChanging(value);
                ReportPropertyChanging("Content");
                _Content = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Content");
                OnContentChanged();
            }
        }
        private global::System.String _Content;
        partial void OnContentChanging(global::System.String value);
        partial void OnContentChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ModifyDate
        {
            get
            {
                return _ModifyDate;
            }
            set
            {
                OnModifyDateChanging(value);
                ReportPropertyChanging("ModifyDate");
                _ModifyDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifyDate");
                OnModifyDateChanged();
            }
        }
        private global::System.DateTime _ModifyDate;
        partial void OnModifyDateChanging(global::System.DateTime value);
        partial void OnModifyDateChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StdMng2015NModel", Name="t_SC")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class t_SC : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 t_SC 对象。
        /// </summary>
        /// <param name="sno">Sno 属性的初始值。</param>
        /// <param name="cno">Cno 属性的初始值。</param>
        public static t_SC Createt_SC(global::System.String sno, global::System.String cno)
        {
            t_SC t_SC = new t_SC();
            t_SC.Sno = sno;
            t_SC.Cno = cno;
            return t_SC;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Sno
        {
            get
            {
                return _Sno;
            }
            set
            {
                if (_Sno != value)
                {
                    OnSnoChanging(value);
                    ReportPropertyChanging("Sno");
                    _Sno = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Sno");
                    OnSnoChanged();
                }
            }
        }
        private global::System.String _Sno;
        partial void OnSnoChanging(global::System.String value);
        partial void OnSnoChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Cno
        {
            get
            {
                return _Cno;
            }
            set
            {
                if (_Cno != value)
                {
                    OnCnoChanging(value);
                    ReportPropertyChanging("Cno");
                    _Cno = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Cno");
                    OnCnoChanged();
                }
            }
        }
        private global::System.String _Cno;
        partial void OnCnoChanging(global::System.String value);
        partial void OnCnoChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> Grade
        {
            get
            {
                return _Grade;
            }
            set
            {
                OnGradeChanging(value);
                ReportPropertyChanging("Grade");
                _Grade = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Grade");
                OnGradeChanged();
            }
        }
        private Nullable<global::System.Int16> _Grade;
        partial void OnGradeChanging(Nullable<global::System.Int16> value);
        partial void OnGradeChanged();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StdMng2015NModel", "FK__t_SC__Cno__08EA5793", "t_Course")]
        public t_Course t_Course
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<t_Course>("StdMng2015NModel.FK__t_SC__Cno__08EA5793", "t_Course").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<t_Course>("StdMng2015NModel.FK__t_SC__Cno__08EA5793", "t_Course").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<t_Course> t_CourseReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<t_Course>("StdMng2015NModel.FK__t_SC__Cno__08EA5793", "t_Course");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<t_Course>("StdMng2015NModel.FK__t_SC__Cno__08EA5793", "t_Course", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StdMng2015NModel", "FK__t_SC__Sno__07F6335A", "t_Student")]
        public t_Student t_Student
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<t_Student>("StdMng2015NModel.FK__t_SC__Sno__07F6335A", "t_Student").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<t_Student>("StdMng2015NModel.FK__t_SC__Sno__07F6335A", "t_Student").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<t_Student> t_StudentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<t_Student>("StdMng2015NModel.FK__t_SC__Sno__07F6335A", "t_Student");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<t_Student>("StdMng2015NModel.FK__t_SC__Sno__07F6335A", "t_Student", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StdMng2015NModel", Name="t_Sdept")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class t_Sdept : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 t_Sdept 对象。
        /// </summary>
        /// <param name="sdeptID">SdeptID 属性的初始值。</param>
        /// <param name="sdeptName">SdeptName 属性的初始值。</param>
        public static t_Sdept Createt_Sdept(global::System.String sdeptID, global::System.String sdeptName)
        {
            t_Sdept t_Sdept = new t_Sdept();
            t_Sdept.SdeptID = sdeptID;
            t_Sdept.SdeptName = sdeptName;
            return t_Sdept;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SdeptID
        {
            get
            {
                return _SdeptID;
            }
            set
            {
                if (_SdeptID != value)
                {
                    OnSdeptIDChanging(value);
                    ReportPropertyChanging("SdeptID");
                    _SdeptID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("SdeptID");
                    OnSdeptIDChanged();
                }
            }
        }
        private global::System.String _SdeptID;
        partial void OnSdeptIDChanging(global::System.String value);
        partial void OnSdeptIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SdeptName
        {
            get
            {
                return _SdeptName;
            }
            set
            {
                OnSdeptNameChanging(value);
                ReportPropertyChanging("SdeptName");
                _SdeptName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SdeptName");
                OnSdeptNameChanged();
            }
        }
        private global::System.String _SdeptName;
        partial void OnSdeptNameChanging(global::System.String value);
        partial void OnSdeptNameChanged();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StdMng2015NModel", "FK__t_Student__SImag__023D5A04", "t_Student")]
        public EntityCollection<t_Student> t_Student
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<t_Student>("StdMng2015NModel.FK__t_Student__SImag__023D5A04", "t_Student");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<t_Student>("StdMng2015NModel.FK__t_Student__SImag__023D5A04", "t_Student", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StdMng2015NModel", Name="t_Student")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class t_Student : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 t_Student 对象。
        /// </summary>
        /// <param name="sno">sno 属性的初始值。</param>
        /// <param name="sGender">SGender 属性的初始值。</param>
        /// <param name="sBirth">SBirth 属性的初始值。</param>
        public static t_Student Createt_Student(global::System.String sno, global::System.String sGender, global::System.DateTime sBirth)
        {
            t_Student t_Student = new t_Student();
            t_Student.sno = sno;
            t_Student.SGender = sGender;
            t_Student.SBirth = sBirth;
            return t_Student;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String sno
        {
            get
            {
                return _sno;
            }
            set
            {
                if (_sno != value)
                {
                    OnsnoChanging(value);
                    ReportPropertyChanging("sno");
                    _sno = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("sno");
                    OnsnoChanged();
                }
            }
        }
        private global::System.String _sno;
        partial void OnsnoChanging(global::System.String value);
        partial void OnsnoChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String sname
        {
            get
            {
                return _sname;
            }
            set
            {
                OnsnameChanging(value);
                ReportPropertyChanging("sname");
                _sname = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("sname");
                OnsnameChanged();
            }
        }
        private global::System.String _sname;
        partial void OnsnameChanging(global::System.String value);
        partial void OnsnameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SGender
        {
            get
            {
                return _SGender;
            }
            set
            {
                OnSGenderChanging(value);
                ReportPropertyChanging("SGender");
                _SGender = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SGender");
                OnSGenderChanged();
            }
        }
        private global::System.String _SGender;
        partial void OnSGenderChanging(global::System.String value);
        partial void OnSGenderChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime SBirth
        {
            get
            {
                return _SBirth;
            }
            set
            {
                OnSBirthChanging(value);
                ReportPropertyChanging("SBirth");
                _SBirth = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SBirth");
                OnSBirthChanged();
            }
        }
        private global::System.DateTime _SBirth;
        partial void OnSBirthChanging(global::System.DateTime value);
        partial void OnSBirthChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Sdept
        {
            get
            {
                return _Sdept;
            }
            set
            {
                OnSdeptChanging(value);
                ReportPropertyChanging("Sdept");
                _Sdept = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Sdept");
                OnSdeptChanged();
            }
        }
        private global::System.String _Sdept;
        partial void OnSdeptChanging(global::System.String value);
        partial void OnSdeptChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] SImage
        {
            get
            {
                return StructuralObject.GetValidValue(_SImage);
            }
            set
            {
                OnSImageChanging(value);
                ReportPropertyChanging("SImage");
                _SImage = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SImage");
                OnSImageChanged();
            }
        }
        private global::System.Byte[] _SImage;
        partial void OnSImageChanging(global::System.Byte[] value);
        partial void OnSImageChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String sIDNum
        {
            get
            {
                return _sIDNum;
            }
            set
            {
                OnsIDNumChanging(value);
                ReportPropertyChanging("sIDNum");
                _sIDNum = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("sIDNum");
                OnsIDNumChanged();
            }
        }
        private global::System.String _sIDNum;
        partial void OnsIDNumChanging(global::System.String value);
        partial void OnsIDNumChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String sEmail
        {
            get
            {
                return _sEmail;
            }
            set
            {
                OnsEmailChanging(value);
                ReportPropertyChanging("sEmail");
                _sEmail = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("sEmail");
                OnsEmailChanged();
            }
        }
        private global::System.String _sEmail;
        partial void OnsEmailChanging(global::System.String value);
        partial void OnsEmailChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SLoc
        {
            get
            {
                return _SLoc;
            }
            set
            {
                OnSLocChanging(value);
                ReportPropertyChanging("SLoc");
                _SLoc = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SLoc");
                OnSLocChanged();
            }
        }
        private global::System.String _SLoc;
        partial void OnSLocChanging(global::System.String value);
        partial void OnSLocChanged();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StdMng2015NModel", "FK__t_SC__Sno__07F6335A", "t_SC")]
        public EntityCollection<t_SC> t_SC
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<t_SC>("StdMng2015NModel.FK__t_SC__Sno__07F6335A", "t_SC");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<t_SC>("StdMng2015NModel.FK__t_SC__Sno__07F6335A", "t_SC", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StdMng2015NModel", "FK__t_Student__SImag__023D5A04", "t_Sdept")]
        public t_Sdept t_Sdept
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<t_Sdept>("StdMng2015NModel.FK__t_Student__SImag__023D5A04", "t_Sdept").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<t_Sdept>("StdMng2015NModel.FK__t_Student__SImag__023D5A04", "t_Sdept").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<t_Sdept> t_SdeptReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<t_Sdept>("StdMng2015NModel.FK__t_Student__SImag__023D5A04", "t_Sdept");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<t_Sdept>("StdMng2015NModel.FK__t_Student__SImag__023D5A04", "t_Sdept", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
